#!/bin/bash
python main_deconfounder.py --obsm 0 --ylayer 10
python main_deconfounder.py --obsm 1 --ylayer 10
python main_deconfounder.py --obsm 2 --ylayer 10
python main_deconfounder.py --obsm 0 --ylayer 20
python main_deconfounder.py --obsm 1 --ylayer 20
python main_deconfounder.py --obsm 2 --ylayer 20
